apiVersion: v1
kind: Service
metadata:
  name: pyworkspace-api
  labels:
    app: pyworkspace
    component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: pyworkspace
    component: api
